version: "3.9"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-nestjs # Liên kết container với mạng kafka-nestjs

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-nestjs # Liên kết container với mạng kafka-nestjs

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - kafka-nestjs # Liên kết container với mạng kafka-nestjs

  api-gate-way:
    container_name: api-gate-way
    image: api-gate-way
    build:
      context: ./gateway/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - zookeeper
      - kafka
      - order-service
      - user-service
    networks:
      - kafka-nestjs # Liên kết container với mạng kafka-nestjs

  order-service:
    container_name: order-service
    # image: order-service
    build:
      context: ./order-service/
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - zookeeper
      - kafka
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    networks:
      - kafka-nestjs # Liên kết container với mạng kafka-nestjs

  user-service:
    container_name: user-service
    # image: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - zookeeper
      - kafka
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    networks:
      - kafka-nestjs # Liên kết container với mạng kafka-nestjs

  order-app-fe:
    container_name: order-application-main
    build:
      context: ./order-application-main
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - api-gate-way
volumes:
  postgres-data:


networks:
  kafka-nestjs:
